name: Tourism MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-and-deploy:

    runs-on: ubuntu-latest

    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r deployment/requirements.txt

      - name: Register Dataset
        run: python src/data_register.py

      - name: Prepare Data
        run: python src/prep.py

      - name: Train Model
        run: python src/train.py

      - name: Deploy to Hugging Face Space
        run: python hosting/hosting.py
